spring:
  application:
    name: register-center
server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
    # 服务注册中心也会将自己作为客户端来尝试注册自己,为true（默认）时自动生效
    register-with-eureka: true
    # 检索服务选项，当设置为True(默认值)时，会进行服务检索,注册中心不负责检索服务。
    fetch-registry: false
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always